require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StructInheritance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/NestedGroups:
    Max: 4

Metrics/ClassLength:
    Max: 200
